In [1]:
# more faster with vectorization
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [5]:
import time
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print(f"Vectorized: {str(1000*(toc - tic))} ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()
print(c)

print(f"For loop: {str(1000*(toc - tic))} ms")


249989.92079291836
Vectorized: 1.2574195861816406 ms
249989.9207929105
For loop: 331.38370513916016 ms


> As you can see vectorized mor quickly than for loop

In [6]:
A = np.array([[56.0, 0., 4.4, 68.0],
            [1.2, 104., 52., 8.],
            [1.8, 135., 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [9]:
cal = A.sum(axis=0) # calculation for columns
print(cal)

[ 59.  239.  155.4  76.9]


In [11]:
cal.shape

(4,)

In [12]:
cal.reshape(1,4)
cal.shape
# Actualy we don't need using reshape(1,4)

(4,)

In [14]:
percentage = 100*A/cal.reshape(1,4)
percentage

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

### Some note with numpy in python

In [15]:
import numpy as np
a = np.random.rand(5) # create variable gaussian random

In [16]:
a

array([0.64912337, 0.0110113 , 0.83901996, 0.75970475, 0.22330966])

In [18]:
a = np.random.rand(5,1)
print(a.shape)
a

(5, 1)


array([[0.06437536],
       [0.17699941],
       [0.76738272],
       [0.47886754],
       [0.02166402]])

In [20]:
x = np.random.rand(8,1)
x.reshape(2,2,2)

array([[[0.10674923, 0.16321115],
        [0.50977475, 0.60423733]],

       [[0.45718074, 0.1394808 ],
        [0.13240342, 0.9044821 ]]])

In [26]:
a=np.random.randn(1,3) # a.shape = (1, 3)a.shape=(1,3)
print(a.shape)
b = np.random.randn(3, 3) # b.shape = (3, 3)b.shape=(3,3)
print(b.shape)
c = a*b
print(c.shape)
print(c)

(1, 3)
(3, 3)
(3, 3)
[[ 0.02011661  0.10011554 -0.42913037]
 [-0.00498151  0.18046612  0.07870981]
 [ 0.03316876  0.00568771 -0.35876056]]


In [28]:
a = np.random.rand(4,3)
b = np.random.rand(4,1)
a + b

array([[0.72227636, 1.31312587, 0.83410191],
       [0.77130933, 0.44510283, 1.25443933],
       [0.52490357, 1.00936624, 1.33724994],
       [1.44284051, 1.02767651, 0.64688948]])

In [31]:
a=np.random.randn(4,3) # a.shape = (4, 3)a.shape=(4,3)
print(a)
b = np.random.randn(1, 3) # b.shape = (1, 3)b.shape=(1,3)
print("-----------------------------------")
print(b)
c = a*b
c.shape

[[ 0.11356579 -0.63552636 -0.42007147]
 [ 0.06560454  0.90110539  1.2569018 ]
 [ 0.80552453 -0.55817517  1.70999216]
 [ 0.60014845 -0.6989544  -0.17021237]]
-----------------------------------
[[ 0.15988885 -1.1649317  -0.24586182]]


(4, 3)

In [5]:
a=np.array([[2,1],[1,3]])
a**2

array([[4, 1],
       [1, 9]])

In [8]:
a = np.random.rand(4,3)
b = np.random.rand(4,1)
c = a.T + b.T
c 

array([[0.98156277, 1.33104808, 0.36452927, 1.10354474],
       [1.16027013, 1.17775585, 0.17683355, 0.90593608],
       [1.06703405, 0.40843251, 0.76567938, 0.79485879]])

In [10]:
a = np.array([[1,2,3], [1,2,3], [1,2,3], [1,2,3]])
b = np.array([[1],[1],[1],[1]])
c = a.T + b.T
c

array([[2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

In [12]:
A = np.random.randn(4,3)

B = np.sum(A, axis = 1, keepdims = True) 
B.shape
B

array([[-0.12896765],
       [-1.39184318],
       [ 1.08051192],
       [-1.89133342]])

In [2]:
import numpy as np
A = np.random.randn(4,3)

B = np.sum(A, axis = 1, keepdims = True) 
B.shape

(4, 1)